sudo: required
services:
  - docker
language: python
env:
  global:
    - DOCKER_REPOSITORY=eventosdobem/dockers
before_install:
  - docker --version
install:
  - docker build -t ${DOCKER_REPOSITORY}:${TRAVIS_COMMIT}-php-5.6-fpm --pull=true ./php-5.6-fpm
  - docker build -t ${DOCKER_REPOSITORY}:${TRAVIS_COMMIT}-php7.1-fpm --pull=true ./php7.1-fpm
  - docker run -d --name php-5.6-fpm ${DOCKER_REPOSITORY}:${TRAVIS_COMMIT}-php-5.6-fpm
  - docker run -d --name php7.1-fpm ${DOCKER_REPOSITORY}:${TRAVIS_COMMIT}-php7.1-fpm
before_script:
  #- env > .env
script:
  - docker ps | grep -q php-5.6-fpm
  - docker ps | grep -q php7.1-fpm