sudo: required
services:
  - docker
language: python
env:
  global:
    # Docker
    - DOCKER_REPOSITORY=eventosdobem/dockers
before_install:
  - docker --version
  #- echo "ENV GIT_SHA ${TRAVIS_COMMIT}" >> Dockerfile
install:
  - docker build -t ${DOCKER_REPOSITORY}:${TRAVIS_COMMIT}-php-5.6-fpm --pull=true ./php-5.6-fpm
  - docker build -t ${DOCKER_REPOSITORY}:${TRAVIS_COMMIT}-php7.1-fpm --pull=true ./php7.1-fpm
before_script:
  #- env > .env
script:
  #- echo 1